---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-vcluster-deployment
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-vcluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: vcluster-gitops1
  targetNamespace: default
  timeout: 2m0s
  wait: true
